# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_detail',
            name='content',
            field=models.TextField(verbose_name='文章内容'),
        ),
    ]
