# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20171124_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='up_count',
            field=models.IntegerField(default=0, verbose_name='评论点赞数'),
        ),
    ]
