# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20171124_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='poll_count',
            new_name='up_count',
        ),
        migrations.AddField(
            model_name='article',
            name='down_count',
            field=models.IntegerField(default=0, verbose_name='点灭数'),
        ),
        migrations.AddField(
            model_name='article_poll',
            name='is_positive',
            field=models.BooleanField(default=1, verbose_name='点赞或踩'),
        ),
    ]
